[global.config]
  as = 100
  router-id = "10.5.0.100"

[[vrfs]]
    [vrfs.config]
        name = "vrf_10"
        id = 10
        rd = "100:10"
        both-rt-list = ["100:10"]

[[vrfs]]
    [vrfs.config]
        name = "vrf_20"
        id = 20
        rd = "100:20"
        both-rt-list = ["100:20"]


[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.4"
    peer-as = 100
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "10.5.0.100"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l2vpn-evpn"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.5"
    peer-as = 100
  [neighbors.route-reflector.config]
    route-reflector-client = true
    route-reflector-cluster-id = "10.5.0.100"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l2vpn-evpn"


[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.1"
    peer-as = 11
    vrf = "vrf_10"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"


[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.2"
    peer-as = 12
    vrf = "vrf_10"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.3"
    peer-as = 13
    vrf = "vrf_20"
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
 
 
