[global.config]
  as = 100
  router-id = "10.5.0.5"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.100"
    peer-as = 100
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "l2vpn-evpn"
