[global.config]
  as = 13
  router-id = "10.5.0.3"

[[neighbors]]
  [neighbors.config]
    neighbor-address = "10.5.0.100"
    peer-as = 100
  [[neighbors.afi-safis]]
    [neighbors.afi-safis.config]
      afi-safi-name = "ipv4-unicast"
