name: Release

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'

    - name: Build binary
      run: |
        cd src
        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ../berg-linux-amd64 ./cmd
        CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -o ../berg-darwin-amd64 ./cmd
        CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -o ../berg-darwin-arm64 ./cmd

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          berg-linux-amd64
          berg-darwin-amd64
          berg-darwin-arm64
